/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/charts/Bar.vue')['default']
    CardForAdd: typeof import('./src/components/cards/CardForAdd.vue')['default']
    CardOfProject: typeof import('./src/components/cards/CardOfProject.vue')['default']
    ChurnStatistics: typeof import('./src/components/ChurnStatistics.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    ListOfStats: typeof import('./src/components/ListOfStats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}
